### ISSUE TITLE
["HELP"] muncul error 401 unauthorized

### ISSUE THREAD

**Issue by DhyasR** [alizaenazet/gamedoc-api#26]
## Detail problem
https://github.com/alizaenazet/gamedoc-api/blob/29223b8731d1102cfa2744d155ea00c7967a4d2a/app/Http/Controllers/GamerController.php#L72C5-L109C6

## The problem assumptions
errornya ada di authorize usernya

## Other information
sebelumnya sudah aku coba di code sebelum aku pull itu masih bisa tapi pas sesudah aku pull itu tiba2 muncul error 401

**Comment by alizaenazet** [comment]
response `401 unauthorized` itu ketika kamu menambahkan middleweare `sanctum` pada endpoint tersebut dan saat aku lihat memang betul kamu menambahkannya terlihat pada [router di file `api.php`](https://github.com/alizaenazet/gamedoc-api/blob/29223b8731d1102cfa2744d155ea00c7967a4d2a/routes/api.php#L56)

yang perlu pastikan adalah saat menguji _API_ tersebut pada request header pastikan menggunakan authorization header dengan tipe bareer token yang didapatkaan saat berhasil dilakukan login pada endpoint `login`.

intinya adalah itu sudah berjalan dengan benar sebagaimana design api harus menyertakan kredensial menggunakan bareer token dari _sanctum_ dan jika tidak mendapati token tersebut akan mengirim response `401 unauthorized`
